Ecommerce_Application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from store.sitemaps import StaticViewSitemap, ProductSitemap, OrderDetailSitemap, CategorySitemap

sitemaps = {
    'static'    :   StaticViewSitemap,
    'product'   :   ProductSitemap,
    'order_detail'   :   OrderDetailSitemap,
    'categories'    :   CategorySitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user_accounts.urls')),
    path('', include('store.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type='text/plain'))
]

handler404 = "store.views.error_404"

store/urls.py
from os import name
from django.urls import path
from . import views

urlpatterns = [
    path("", views.Home.as_view(), name='home'),
    path('category/<int:id>', views.Category.as_view(), name='category_products'),
    path('product/<int:id>/', views.product_detail, name="product"),

    path("my-orders", views.myOrders, name="my_orders"),
    path("order-details/<int:id>", views.orderDetail, name='order_detail'),
    path("checkout/", views.CheckoutView.as_view(), name="checkout"),
    path("confirm-order/<str:session_ID>", views.ConfirmOrderView.as_view(), name="confirm-order"),
    path("place-order/<str:session_ID>", views.placeOrder, name="placeOrder"),
    path('cancel-order/<int:pk>', views.CancelOrder, name='canceled'),

    path('webhook/stripe/', views.stripeWebhookView, name='stripe-webhook'),

    path('newsletter-subscription', views.NewsletterSubscriptionView, name='subscribe-to-newsletter'),
    path('contact-us', views.ContactUSView.as_view(), name='contact-us'),
    # View to sync products with stripe store
    path('sync-with-stripe', views.SyncDataWithStripe, name='sync-with-stripe'),
]

user_accounts/urls.py
from os import name
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import (
    LoginForm, 
    MyPasswordResetForm,
    MySetPasswordForm,
    MyPasswordChangeForm,
)
from . import views

urlpatterns = [
    path("register", views.customerRegistration.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='login'), name='logout'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html', form_class=MyPasswordResetForm), 
        name='password_reset'
    ),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'), 
        name='password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset_confirm.html', 
        form_class=MySetPasswordForm), 
        name='password_reset_confirm'
    ),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'), 
        name='password_reset_complete'
    ),
    
    path("profile/", views.profile, name="profile"),
    path("update-profile/", views.UpdateProfile.as_view(), name="update-profile"),
    path("address-book", views.addressBook.as_view(), name="address_book"),
    path("delete-address/<int:pk>", views.DeleteAddress.as_view(), name="delete-address"),
    path('password-change/', auth_views.PasswordChangeView.as_view(
        template_name='passwordchange.html', 
        form_class=MyPasswordChangeForm, 
        success_url='accounts/password-changed/'), 
        name='passwordchange'
    ),
    path('password-changed/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_reset_complete.html'), 
        name='passwordchangedone'
    ),

]

user_accounts/models.py
from django.db import models
from django.contrib.auth.models import User

membership_choices=[
    ("B","Bronze"),
    ("S","Silver"),
    ("G","Gold")

]

gender_choices=[
    ("M","Male"),
    ("F","Female"),
    ("O","Other")

]

# Tbale to store users profile information
class Customer(models.Model):
    phone=models.CharField(max_length=255, null=True, blank=True)
    gender=models.CharField(max_length=1, choices=gender_choices, null=True, blank=True)
    Birth_date=models.DateField(null=True, blank=True)
    membership=models.CharField(max_length=1, choices=membership_choices, default="B")
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.pk}'

    def get_latest_address(self):
        return Address.objects.filter(user=self.user)[0]

    class Meta:
        verbose_name_plural = 'Customers'

# Table to store users/customer adrrees
class Address(models.Model):
    street=models.CharField(max_length=255)
    city=models.CharField(max_length=255)
    user=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.street

    class Meta:
        verbose_name_plural = 'Address'

user_accounts/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UsernameField,
    UserCreationForm,
    PasswordResetForm,
    SetPasswordForm,
    PasswordChangeForm,
)
from django.forms import fields, widgets
from django.contrib.auth.models import User
from django.utils.translation import gettext,gettext_lazy as _
from django.contrib.auth import password_validation
from .models import Address


class LoginForm(AuthenticationForm):
    username = UsernameField(widget = forms.TextInput(
        attrs = {'autofocus':True,
            'class':'form-control'
        }
    ))
    password = forms.CharField(label = _('Password'),
        strip = False,
        widget = forms.PasswordInput(
            attrs = {'autocomplete':'current-password', 'autofocus':True, 'class':'form-control'}
        )
    )

class CustomerRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label = 'Password',
        widget = forms.PasswordInput(attrs = {'class':'form-control'})
    )
    password2 = forms.CharField(label = 'Confirm Password (again)',
        widget = forms.PasswordInput(attrs = {'class':'form-control'})
    )
    email = forms.CharField(required = True, 
        widget = forms.EmailInput(attrs = {'class':'form-control'})
    )
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {
            'email':'Email',
            'first_name':"First Name",
            'last_name':"Last Name"
        }
        widgets = {
            'username':forms.TextInput(attrs = {'class':'form-control'}),
            'first_name':forms.TextInput(attrs = {'class':'form-control'}),
            'last_name':forms.TextInput(attrs = {'class':'form-control'})
        }

class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(label = _('Email'),
        max_length = 254,
        widget = forms.EmailInput(
            attrs = {'autocomplete':'email','class':'form-control'}
        )
    )

class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label = 'New Password',
        widget = forms.PasswordInput(attrs = {'autocomplete':'new-password','class':'form-control'}),
        help_text = password_validation.password_validators_help_text_html()
    )
    new_password2 = forms.CharField(label = 'Confirm New Password',
        widget = forms.PasswordInput(attrs = {'autocomplete':'new-password','class':'form-control'})
    )

class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label = _('Old Password'),
        strip = False,
        widget = forms.PasswordInput(
            attrs = {'autocomplete':'current-password','class':'form-control'}
        )
    )
    new_password1 = forms.CharField(label = 'New Password',
        widget = forms.PasswordInput(
            attrs = {'autocomplete':'new-password','class':'form-control'}
        ),
        help_text = password_validation.password_validators_help_text_html()
    )
    new_password2 = forms.CharField(
        label = 'Confirm New Password',
        widget = forms.PasswordInput(
            attrs = {'autocomplete':'new-password','class':'form-control'}
        )
    )

class AddAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['street','city']
        widgets = {
            'street':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            }

user_accounts/views.py
from django.shortcuts import redirect, render ,HttpResponse, get_object_or_404 
from django.views import View
from django.contrib import messages
from django.contrib.auth.models import User
from .models import (
	Customer,
	Address
)
from store.models import Categories
from .forms import (
	CustomerRegistrationForm,
	AddAddressForm,
)
from datetime import datetime

# View responsible for registering new users
class customerRegistration(View):
	template_name = "customerRegistration.html"

	def get(self , request):
		context = {
		'form'	:	CustomerRegistrationForm()
		}
		return render(request, self.template_name, context)

	def post(self, request):
		form = CustomerRegistrationForm(request.POST)
		# Checking if form is valid or it contains errors
		if form.is_valid():
			# Form is valid
			form = form.save(commit=False) # Setting form to not be saved directly as we need pk of the instance
			form.save()
			# Creating customer profile for the resitered user
			customer_obj = Customer()
			customer_obj.user = form
			customer_obj.save()
			messages.success(request,'Congratulations!! Registerion Completed')
			return redirect('home')

		return render(request, self.template_name, {"form":form})

# User responsible for rendering users profile page
def profile(request):
	# Checking if logged in user has customer profile
	try:
		customer = Customer.objects.get(user=request.user)

	except Exception as exe:
		# Logged in user doesn't have a customer profile. Creating new customr profile for the user
		customer = Customer(user=request.user)
		customer.save()

	context = {
		'customer'	:	customer,
		"categories"	:	Categories.objects.all(),
	}
	return render(request, "profile.html", context)

class UpdateProfile(View):
	template_name = 'update_profile.html'

	def get(self, request):
		current_user = request.user
		try:
			customer = Customer.objects.get(user=current_user)

		except Exception as exe:
			return redirect('home')

		context = {
			'customer'	:	customer,
			"categories"	:	Categories.objects.all(),
		}
		return render(request, self.template_name, context)

	def post(self, request):
		current_user = request.user
		customer = Customer.objects.get(user=current_user)

		first_name = request.POST.get('first_name')
		last_name = request.POST.get('last_name')
		email = request.POST.get('email')
		phone = request.POST.get('phone')
		Birth_date = request.POST.get('birth_date')
		gender = request.POST.get('gender')
		Birth_date = datetime.strptime(Birth_date, '%Y-%M-%d')

		current_user.first_name = first_name
		current_user.last_name = last_name
		current_user.email = email
		current_user.save()

		customer.phone = phone
		customer.gender = gender
		customer.Birth_date = Birth_date
		customer.save()

		messages.success(request, 'Profile information updated successfully')
		return redirect('profile')

class addressBook(View):
	template_name = "address_book.html"

	def get(self,request):
		form = AddAddressForm()
		# Getting users adrress from database
		add = Address.objects.filter(user=request.user)
		context = {
			'form'	:	form,
			'add'	:	add,
			"categories"	:	Categories.objects.all(),
		}
		return render(request, self.template_name, context)

	def post(self,request):
		form = AddAddressForm(request.POST)
		user = request.user
		if form.is_valid():
			street = form.cleaned_data['street']
			city = form.cleaned_data['city']
			address_obj = Address()
			address_obj.street = street
			address_obj.city = city
			address_obj.user = user
			address_obj.save()
			messages.success(request,' Address added successfully!')

		add = Address.objects.filter(user=request.user)
		context = {
			'form'	:	form,
			'add'	:	add,
			"categories"	:	Categories.objects.all(),
		}
		return render(request, self.template_name, context)

class DeleteAddress(View):

	def get(self, request, pk):
		address = Address.objects.get(pk=pk)
		address.delete()
		messages.success(request, 'Address removed')
		return redirect('address_book')

user_accounts/templates/address_book.html
{% extends "base.html" %}
{% block title %}Address Book{% endblock %}
{%block content%}		
	<!-- Product Style -->
	<section class="product-area shop-sidebar shop section">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-4 col-12">
					<div class="shop-sidebar">
							<!-- Single Widget -->
							<div class="single-widget category">
								<h3 class="title">Manage Your Account</h3>
								<ul class="categor-list">
									
									<li ><a  href="{% url 'profile'%}">My Profile</a></li>
									<li><a href="{% url 'address_book'%}">Address Book</a></li>
                                    	
								</ul>
                                <br>
                                <h3 class="title">My Orders</h3>
								<ul class="categor-list">
									<li><a href="#">All Orders</a></li>

                                    	
								</ul>
							</div>
							<!--/ End Single Widget -->
				
					</div>
				</div>
				<div class="col-lg-9 col-md-8 col-12">
					<div class="row">
                        <div class="col-12">
                            <h3>My Address Book</h3>
                        </div>
                        
                        <div class="card col-12 mt-2">
                            <div class="card-body">
								
								<form action="" method="post">
									{% csrf_token %}
									{% for fm in form %}
									<div class="form-group col-lg-6 mb-3">
									  {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
									</div>
									{% endfor %}
									<div class="col-12 mt-3">
									  <button type="submit" class="btn btn-primary">Submit</button>
									</div>
									{% if form.non_field_errors %}
										{% for error in form.non_field_errors %}
											<p class="alert alert-danger my-3">{{error}}</p>
										{% endfor %}
									{% endif %}
								  </form>
								  {% if messages %}
								  {% for message in messages %}
									<p {% if message.tags %} class="alert alert-{{message.tags}} my-5" {% endif %}>{{message}}</p>
								  {% endfor %}
							  {% endif %}
                                  <!-- <div class="row"><button class="btn btn primary"></button></div> -->
                                  
                            </div>
                          </div>
						  <div class="card col-12 mt-2">
                            <div class="card-body">
								
								<table class="table">
									<thead>
									  <tr>
										<th scope="col">Address</th>
										<th scope="col">City</th>
										<th scope="col">Street</th>
										<th scope="col">Action</th>
									  </tr>
									</thead>
									<tbody>
									{% for x in add%}
									  <tr>
										<th scope="row">{{forloop.counter}}</th>
										<td>{{x.city}}</td>
										<td>{{x.street}}</td>
										<td><a class="btn btn-primary" href="{% url 'delete-address' x.pk %}">Delete</a></td>
									  </tr>
									{% endfor%}
									  
									</tbody>
								  </table>
                                  <!-- <div class="row"><button class="btn btn primary"></button></div> -->
                                  
                            </div>
                          </div>

					</div>
					
				</div>
			</div>
		</div>
	</section>
	<!--/ End Product Style 1  -->	
{%endblock%}

user_accounts/templates/customerRegistration.html
{% extends 'base.html' %}
{% block title %}Customer Registration{% endblock title %}
{% block content %}
   <div class="container">
      <div class="row my-3">
         <div class="col-sm-6 offset-sm-3">
            <h3>Customer Registration</h3>
            <hr>

            <form method="post" novalidate class="shadow p-5">
               {% if messages %}
                  {% for message in messages %}
                     <p {% if message.tags %} class="alert alert-{{message.tags}} mb-5" {% endif %}>{{message}}</p>
                  {% endfor %}
               {% endif %}
               {% csrf_token %}
               {% for fm in form %}
                  <div class="form-group mb-3">
                     {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                  </div>
               {% endfor %}
               <input type="submit" value="Submit" class="btn btn-primary">
               <br>
               <div class="text-center text-primary fw-bold">
                  <small>Existing User ? <a href="{% url 'login' %}" class="text-danger">Login Now</a></small>
               </div>
               {% if form.non_field_errors %}
                  {% for error in form.non_field_errors %}
                     <p class="alert alert-danger my-3">{{error}}</p>
                  {% endfor %}
               {% endif %}
            </form>
         </div>
      </div>
   </div>
{% endblock content %}

user_accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}
    <div class="container">
        <div class="row my-3">
            <div class="col-sm-6 offset-sm-3">
                <h3>Login</h3>
                <hr>
                <form action="" method="post" novalidate class="shadow p-5">
                    {% csrf_token %}
                    {% for fm in form %}
                        <div class="form-group">
                            {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                        </div>
                    {% endfor %}
                    <small><a href="{% url 'password_reset' %}">Forgot Password ?</a></small> <br>
                    <input type="submit" class="btn btn-primary mt-4" value="Login">
                    <br>
                    <div class="text-center text-primary fw-bold"><small>New to E-Shop? <a
                                href="{% url 'register' %}" class="text-danger">Create an Account</a> </small>
                    </div>
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <p class="alert alert-danger my-3">{{error}}</p>
                        {% endfor %}
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

user_accounts/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}Reset Password{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Reset Password</h3>
            <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group">
                    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary mt-4" value="Save">
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{error}}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}

user_accounts/templates/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Change Password Done{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-5">
        <div class="col-sm-6 offset-sm-3">
            <h4>Password Setup Completed!</h4>
            <div>
                <iframe src="https://giphy.com/embed/ibolLe3moqHE3PQTtk" width="200" height="200" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

user_accounts/templates/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Password Reset Done{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Password Reset Confirm</h3>
            <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                <div class="form-group">
                    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                </div>
                {% endfor %}
                <input type="submit" class="btn btn-primary mt-4" value="Submit">
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{error}}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}

user_accounts/templates/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password Reset Done{% endblock title %}
{% block content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h4 class="alert-heading">Well done!</h4>
            <p>Email has been sent with instructions to reset your password. <b>Check Your Email!</b></p>
        </div>
    </div>
</div>
{% endblock content %}

user_accounts/templates/passwordchange.html
{% extends 'base.html' %}
{% block title %}Change Password{% endblock title %}
{% block content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome {{request.user.first_name}} {{request.user.last_name}}</h3>
  
  <div class="col-sm-9 offset-sm-1">
    <h3>Change Password</h3>
    <hr>
    <form action="" method="post" class="shadow-sm p-5" novalidate>
        {% csrf_token %}
        {% for fm in form %}
            <div class="form-group">
                {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
            </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary mt-4" value="Save">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="alert alert-danger my-3">{{error}}</p>
            {% endfor %}
        {% endif %}
    </form>
  </div>
 </div>
</div>
{% endblock content %}

user_accounts/templates/profile.html
{% extends "base.html" %}
{% block title %}{{request.user.get_full_name}}'s Profile{% endblock %}
{%block content%}		
		<!-- Product Style -->
		<section class="product-area shop-sidebar shop section">
			<div class="container">
				<div class="row">
					<div class="col-lg-3 col-md-4 col-12">
						<div class="shop-sidebar">
								<!-- Single Widget -->
								<div class="single-widget category">
									<h3 class="title">Manage Your Account</h3>
									<ul class="categor-list">
										<li><a href="{% url 'profile'%}">My Profile</a></li>
										<li><a href="{% url 'address_book' %}">Address Book</a></li>
									</ul>
                  <br>
                  <h3 class="title">My Orders</h3>
									<ul class="categor-list">
										<li><a href="{% url 'my_orders' %}">All Orders</a></li>
									</ul>
								</div>
								<!--/ End Single Widget -->
						</div>
					</div>
					<div class="col-lg-9 col-md-8 col-12">
						<div class="row">
              <div class="col-12 pl-0">
                <h3>My profile</h3>
              </div>
                            
              <div class="card col-12 mt-2">
                <div class="card-body">
                  <table class="table">
                    <tbody>
                      <tr>
                        <th scope="row">First Name:</th>
                        <td>{{customer.user.first_name}}</td>
			                </tr>
                      <tr>
                        <th scope="row">Last Name:</th>
                        <td>{{request.user.last_name}}</td>
                      </tr>
                      <tr>
                        <th scope="row">Email:</th>
                        <td>{{customer.user.email}}</td>
                      </tr>
                      <tr>
                        <th scope="row">Phone</th>
                        <td>{{customer.phone}}</td>
                      </tr>
                      <tr>
                        <th scope="row">Membership</th>
                        <td>{{customer.membership}}</td>
                      </tr>
                      <tr>
                        <th scope="row">Birth Date</th>
                        <td style="border-bottom: 1px solid #e9ecef">{{customer.Birth_date}}</td>
                      </tr>
                      <tr>
                        <th scope="row">Gender</th>
                        <td style="border-bottom: 1px solid #e9ecef">{{customer.gender}}</td>
                      </tr>
                      <tr>
                        <th scope="row" class="pl-0">
                        	<a href="{% url 'passwordchange' %}" class="btn btn primary text-white">Change Password</a>
                        	<a href="{% url 'update-profile' %}" class="btn btn primary text-white ml-3">Update Profile</a>
                        </th>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </div>
						</div>

					</div>
				</div>
			</div>
		</section>
		<!--/ End Product Style 1  -->			
{%endblock%}

user_accounts/templates/update_profile.html
{% extends 'base.html' %}
{% block title %}Update Profile{% endblock %}
{% block content %}
<div class="container my-5">
 <div class="row">
 <h3>Welcome {{request.user.username}}</h3>
  
  <div class="col-sm-9 offset-sm-1">
    <h3>Update Profile Information</h3>
    <hr>
    <form action="" method="post" class="shadow-sm p-5" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label for="id_first_name" class="panel-body-text">First Name:</label>
            <input type="mobile" class="form-control" id="id_first_name" value="{{ customer.user.firstname }}" name="first_name">
        </div>
        <div class="form-group">
            <label for="id_last_name" class="panel-body-text">Last Name:</label>
            <input type="mobile" class="form-control" id="id_last_name" value="{{ customer.user.lastname }}" name="last_name">
        </div>
        <div class="form-group">
            <label for="id_email" class="panel-body-text">Email:</label>
            <input type="mobile" class="form-control" id="id_email" value="{{ customer.user.email }}" name="email">
        </div>
        <div class="form-group">
            <label for="id_phone" class="panel-body-text">Phone:</label>
            <input type="text" class="form-control" id="id_phone" value="{{ customer.phone }}" name="phone">
        </div>
        <div class="form-group">
            <label for="id_birth_date" class="panel-body-text">Birth Date:</label>
            <input type="date" class="form-control" id="id_birth_date" value="{{ customer.Birth_date|date:'Y-m-d' }}" name="birth_date">
        </div>
        <div class="choices-container">
      		<label class="checkbox-container mr-3">
					  <input type="radio" class="bolean-radio-checkbox" name="gender" value="M" {% if customer.gender == 'M' %}checked{% endif %} required>
					  <span class="checkmark"></span> Male
					</label>
					<label class="checkbox-container mr-3">
					  <input type="radio" class="bolean-radio-checkbox" name="gender" value="F" {% if customer.gender == 'F' %}checked{% endif %} required>
					  <span class="checkmark"></span> Female
					</label>
					<label class="checkbox-container mr-3">
					  <input type="radio" class="bolean-radio-checkbox" name="gender" value="O" {% if customer.gender == 'O' %}checked{% endif %} required>
					  <span class="checkmark"></span> Other
					</label>
        </div>
        <button class="btn btn primary mt-4">Update</button>
    </form>
  </div>
 </div>
</div>
{% endblock content %}